---
project_name: galaxy
dist: ./build/dist

archive:
  format: tar.gz

builds:
  - binary: galaxy
    main: ./cmd/galaxy/galaxy.go
    goos:
      - linux
    env:
      - CGO_ENABLED=0
    flags:
      -a
    goarch:
      - amd64