---
language: go
go:
  - 1.11.x
install: true
before_script:
  - docker-compose up -d
  - .ci/install-vault.sh
  - .ci/bootstrap-vault.sh
  - .ci/install-minikube.sh
  - .ci/install-helm.sh
  - make dep
script:
  - export GALAXY_VAULT_ROLE_ID=$(grep ROLE_ID .env |awk -F '"' '{print $2}')
  - export GALAXY_VAULT_SECRET_ID=$(grep SECRET_ID .env |awk -F '"' '{print $2}')
  - export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
  - make bootstrap
  - make
  - make test
  - make integration
after_success:
  - make codecov
