---
language: go
go:
  - 1.11.x
install: true
before_script:
  - docker-compose -d
  - .ci/bootstrap-vault.sh
  - .ci/install-minikube.sh
  - .ci/install-helm.sh
  - make dep
script:
  - export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
  - make bootstrap
  - make
  - make test
  - make integration
after_success:
  - make codecov
