---
language: go
go:
  - 1.11.x
install: true
before_script:
  - .ci/install-minikube.sh
  - .ci/install-helm.sh
  - make dep
script:
  - make bootstrap
  - make
  - make test
  # - make integration
after_success:
  - make codecov
